import { QuestionPair, WordPair } from './types';

export const COLORS = {
  background: '#0F0F14',
  card: '#1A1A22',
  primary: '#7C5CFF',
  secondary: '#4CC9F0',
  text: '#FFFFFF',
  textMuted: '#B3B3C6',
  danger: '#E5484D',
};

export const ANIMATION_DURATION = 0.25;

// GAME 1: NUMBER JUSTIFY (200 PAIRS)
export const NUMBER_QUESTIONS: QuestionPair[] = [
  // --- NUMERIC QUESTIONS (100) ---
  { safe: "How many slices of pizza can you eat?", impostor: "How many toddlers could you fight?", type: 'number' },
  { safe: "Rate your driving skills (1-10)", impostor: "Rate your honesty (1-10)", type: 'number' },
  { safe: "What age is 'old'?", impostor: "What age is 'young'?", type: 'number' },
  { safe: "How much ($) for a burger?", impostor: "How much ($) for a kidney?", type: 'number' },
  { safe: "Hours you sleep per night?", impostor: "Hours you work per day?", type: 'number' },
  { safe: "How many countries have you visited?", impostor: "How many times have you been arrested?", type: 'number' },
  { safe: "Rate your cooking (1-10)", impostor: "Rate your singing (1-10)", type: 'number' },
  { safe: "Ideal temperature (Celsius)?", impostor: "Age of your first crush?", type: 'number' },
  { safe: "How many apps on your phone?", impostor: "How many secrets do you have?", type: 'number' },
  { safe: "Desired number of kids?", impostor: "Number of exes?", type: 'number' },
  { safe: "How many pushups can you do?", impostor: "How many lies told today?", type: 'number' },
  { safe: "Rate your style (1-10)", impostor: "Rate your hygiene (1-10)", type: 'number' },
  { safe: "Days without a shower?", impostor: "Weeks without calling mom?", type: 'number' },
  { safe: "How many cups of coffee per day?", impostor: "How many enemies do you have?", type: 'number' },
  { safe: "Year you want to retire?", impostor: "Year you think the world ends?", type: 'number' },
  { safe: "How many siblings do you have?", impostor: "How many people have you ghosted?", type: 'number' },
  { safe: "Rate your patience (1-10)", impostor: "Rate your ego (1-10)", type: 'number' },
  { safe: "How many pets have you owned?", impostor: "How many laws have you broken?", type: 'number' },
  { safe: "Minutes to get ready in the morning?", impostor: "Minutes you'd last in a horror movie?", type: 'number' },
  { safe: "How many books did you read last year?", impostor: "How many times did you cry last month?", type: 'number' },
  // ... (Adding 80 more numeric pairs for variety)
  { safe: "Rate the last movie you saw (1-10)", impostor: "Rate your looks (1-10)", type: 'number' },
  { safe: "How many pairs of shoes do you own?", impostor: "How many regrets do you have?", type: 'number' },
  { safe: "How many messages are unread?", impostor: "How many people hate you?", type: 'number' },
  { safe: "Percentage of phone battery right now?", impostor: "Your chance of going to heaven (%)?", type: 'number' },
  { safe: "How many times do you check your phone per hour?", impostor: "How many mirrors are in your house?", type: 'number' },
  { safe: "What is your lucky number?", impostor: "How many dates have you been on?", type: 'number' },
  { safe: "How many states/provinces have you lived in?", impostor: "How many people have you kissed?", type: 'number' },
  { safe: "Rate your tech-savviness (1-10)", impostor: "Rate your common sense (1-10)", type: 'number' },
  { safe: "How many minutes is your commute?", impostor: "How many minutes can you hold your breath?", type: 'number' },
  { safe: "How many languages can you speak?", impostor: "How many personalities do you have?", type: 'number' },
  { safe: "Ideal number of houseguests?", impostor: "Number of people you'd save in a fire?", type: 'number' },
  { safe: "Rate your spice tolerance (1-10)", impostor: "Rate your pain tolerance (1-10)", type: 'number' },
  { safe: "How many hours of TV per week?", impostor: "How many hours do you spend staring at a wall?", type: 'number' },
  { safe: "Number of keys on your keyring?", impostor: "Number of people you've blocked?", type: 'number' },
  { safe: "What is a 'short' height for a man?", impostor: "What is a 'long' time in prison?", type: 'number' },
  { safe: "How many pillows do you sleep with?", impostor: "How many bodies are buried in your yard?", type: 'number' },
  { safe: "How many times a week do you exercise?", impostor: "How many times a week do you lie to yourself?", type: 'number' },
  { safe: "Rate your social skills (1-10)", impostor: "Rate your dancing (1-10)", type: 'number' },
  { safe: "How many tabs are open on your browser?", impostor: "How many ghosts have you seen?", type: 'number' },
  { safe: "What grade were you in when you had your first kiss?", impostor: "How many drinks does it take to get you drunk?", type: 'number' },
  { safe: "How many selfies are on your phone?", impostor: "How many times have you been to the hospital?", type: 'number' },
  { safe: "What is the perfect age to get married?", impostor: "How many years until the robots take over?", type: 'number' },
  { safe: "How many people are in your 'Inner Circle'?", impostor: "How many people would come to your funeral?", type: 'number' },
  { safe: "How many glasses of water today?", impostor: "How many times have you been heartbroken?", type: 'number' },
  { safe: "Rate your sense of humor (1-10)", impostor: "Rate your luck in life (1-10)", type: 'number' },
  { safe: "How many cousins do you have?", impostor: "How many people's names have you forgotten today?", type: 'number' },
  { safe: "How many times a day do you brush your teeth?", impostor: "How many times a day do you think about money?", type: 'number' },
  { safe: "Rate your singing voice (1-10)", impostor: "Rate your ability to keep a secret (1-10)", type: 'number' },
  { safe: "How many photos did you take today?", impostor: "How many times have you failed at something?", type: 'number' },
  { safe: "How many alarms do you set for the morning?", impostor: "How many voices are in your head?", type: 'number' },
  { safe: "How many coins are in your pocket/wallet?", impostor: "How many times have you cheated in a game?", type: 'number' },
  { safe: "What is your dream house's bedroom count?", impostor: "How many people have you seen naked?", type: 'number' },
  { safe: "Rate your memory (1-10)", impostor: "Rate your level of paranoia (1-10)", type: 'number' },
  { safe: "How many minutes to eat a meal?", impostor: "How many minutes until you get bored of this conversation?", type: 'number' },
  { safe: "How many windows are in your bedroom?", impostor: "How many people are you currently stalking?", type: 'number' },
  { safe: "Rate the current year so far (1-10)", impostor: "Rate your willpower (1-10)", type: 'number' },
  { safe: "How many hats do you own?", impostor: "How many conspiracy theories do you believe?", type: 'number' },
  { safe: "How many chairs are in your house?", impostor: "How many times have you faked a laugh today?", type: 'number' },
  { safe: "How many times have you moved houses?", impostor: "How many times have you been fired?", type: 'number' },
  { safe: "Rate your cooking (1-10)", impostor: "Rate your flirting (1-10)", type: 'number' },
  { safe: "How many plants are in your home?", impostor: "How many people's numbers do you have memorized?", type: 'number' },
  { safe: "How many hours of sunshine do you need?", impostor: "How many hours until you lose your mind?", type: 'number' },
  { safe: "Rate your level of fitness (1-10)", impostor: "Rate your level of laziness (1-10)", type: 'number' },
  { safe: "How many times do you sneeze in a row?", impostor: "How many crimes could you get away with?", type: 'number' },
  { safe: "How many pairs of socks do you own?", impostor: "How many personalities are you juggling?", type: 'number' },
  { safe: "Rate your navigation skills (1-10)", impostor: "Rate your self-control (1-10)", type: 'number' },
  { safe: "How many mugs do you have in your cabinet?", impostor: "How many people have you made cry?", type: 'number' },
  { safe: "How many times a day do you check the fridge?", impostor: "How many times a day do you check your bank account?", type: 'number' },
  { safe: "Rate your ability to handle stress (1-10)", impostor: "Rate your ability to lie (1-10)", type: 'number' },
  { safe: "How many people have you texted today?", impostor: "How many people have you thought about killing?", type: 'number' },
  { safe: "What is the most you'd pay for a t-shirt?", impostor: "How many lives are you worth?", type: 'number' },
  { safe: "How many stairs are in your house?", impostor: "How many skeletons are in your closet?", type: 'number' },
  { safe: "Rate your handwriting (1-10)", impostor: "Rate your level of maturity (1-10)", type: 'number' },
  { safe: "How many towels do you own?", impostor: "How many people have you betrayed?", type: 'number' },
  { safe: "How many spoons are in your kitchen?", impostor: "How many people do you secretly despise?", type: 'number' },
  { safe: "Rate your fashion sense (1-10)", impostor: "Rate your mental stability (1-10)", type: 'number' },
  { safe: "How many doors are in your home?", impostor: "How many exit strategies do you have?", type: 'number' },
  { safe: "How many miles do you walk a day?", impostor: "How many miles would you walk to bury a body?", type: 'number' },
  { safe: "Rate your ability to focus (1-10)", impostor: "Rate your thirst for power (1-10)", type: 'number' },
  { safe: "How many lightbulbs are in your room?", impostor: "How many great ideas have you actually had?", type: 'number' },
  { safe: "How many remote controls do you have?", impostor: "How many people do you control?", type: 'number' },
  { safe: "Rate your empathy (1-10)", impostor: "Rate your arrogance (1-10)", type: 'number' },
  { safe: "How many pens do you have on your desk?", impostor: "How many names are on your 'list'?", type: 'number' },
  { safe: "How many hours of music do you listen to?", impostor: "How many hours of silence can you stand?", type: 'number' },
  { safe: "Rate your first impression (1-10)", impostor: "Rate your dark side (1-10)", type: 'number' },
  { safe: "How many apps did you delete recently?", impostor: "How many memories did you suppress?", type: 'number' },
  { safe: "How many times do you check the locks?", impostor: "How many people are watching you?", type: 'number' },
  { safe: "Rate your optimism (1-10)", impostor: "Rate your cynicism (1-10)", type: 'number' },
  { safe: "How many birthdays do you remember?", impostor: "How many faces do you have?", type: 'number' },
  { safe: "How many shoes are by your front door?", impostor: "How many people are following you?", type: 'number' },
  { safe: "Rate your life satisfaction (1-10)", impostor: "Rate your acting skills (1-10)", type: 'number' },
  { safe: "How many times have you been to the cinema this year?", impostor: "How many times have you been caught lying?", type: 'number' },
  { safe: "How many people are in your contacts?", impostor: "How many people actually like you?", type: 'number' },
  { safe: "Rate your productivity (1-10)", impostor: "Rate your guilt (1-10)", type: 'number' },
  { safe: "How many blankets do you own?", impostor: "How many layers do you have?", type: 'number' },
  { safe: "How many times do you wash your hands?", impostor: "How many sins do you have to wash away?", type: 'number' },
  { safe: "Rate your charisma (1-10)", impostor: "Rate your toxicity (1-10)", type: 'number' },
  { safe: "How many cups are in your sink?", impostor: "How many failures are in your past?", type: 'number' },
  { safe: "How many people did you talk to today?", impostor: "How many people did you manipulate today?", type: 'number' },
  { safe: "Rate your level of excitement (1-10)", impostor: "Rate your level of dread (1-10)", type: 'number' },

  // --- TEXT / WORD BASED (100) ---
  { safe: "What is your favorite breakfast food?", impostor: "What is the weirdest thing you've eaten?", type: 'text' },
  { safe: "Where would you go for a dream vacation?", impostor: "Where would you hide a dead body?", type: 'text' },
  { safe: "What is the best job in the world?", impostor: "What is the most dangerous job?", type: 'text' },
  { safe: "Name a movie everyone should watch.", impostor: "Name a movie that made you cry.", type: 'text' },
  { safe: "What is the most useful invention?", impostor: "What is the scariest invention?", type: 'text' },
  { safe: "What is your best quality?", impostor: "What is your biggest secret?", type: 'text' },
  { safe: "What animal would you like as a pet?", impostor: "What animal would most likely kill you?", type: 'text' },
  { safe: "Who is your hero?", impostor: "Who is your arch-nemesis?", type: 'text' },
  { safe: "What is your favorite hobby?", impostor: "What is your guilty pleasure?", type: 'text' },
  { safe: "What is the most beautiful place on Earth?", impostor: "What is the most terrifying place on Earth?", type: 'text' },
  { safe: "What is your favorite color?", impostor: "What color is your soul?", type: 'text' },
  { safe: "What is the best way to travel?", impostor: "What is the best way to escape?", type: 'text' },
  { safe: "What is your favorite fruit?", impostor: "What is the forbidden fruit?", type: 'text' },
  { safe: "What is your favorite song?", impostor: "What song would play at your funeral?", type: 'text' },
  { safe: "What is the best sport?", impostor: "What is the most violent sport?", type: 'text' },
  { safe: "What is your dream car?", impostor: "What car would you use for a getaway?", type: 'text' },
  { safe: "What is the best dessert?", impostor: "What is your last meal?", type: 'text' },
  { safe: "What is your favorite season?", impostor: "What season is the worst for survival?", type: 'text' },
  { safe: "What is the best flower?", impostor: "What flower is the most poisonous?", type: 'text' },
  { safe: "What is your favorite book?", impostor: "What book contains the dark truth?", type: 'text' },
  { safe: "What is the best drink?", impostor: "What is the strongest poison?", type: 'text' },
  { safe: "What is your favorite weather?", impostor: "What weather is best for a crime?", type: 'text' },
  { safe: "What is the best city in the world?", impostor: "What city is the most corrupt?", type: 'text' },
  { safe: "What is your favorite holiday?", impostor: "What holiday do you dread the most?", type: 'text' },
  { safe: "What is the best pizza topping?", impostor: "What is a crime against pizza?", type: 'text' },
  { safe: "What is your favorite school subject?", impostor: "What subject did you fail at?", type: 'text' },
  { safe: "What is the best superpower?", impostor: "What is the most evil power?", type: 'text' },
  { safe: "What is your favorite smell?", impostor: "What is the smell of fear?", type: 'text' },
  { safe: "What is the best gift you've received?", impostor: "What is the worst thing you've ever done?", type: 'text' },
  { safe: "What is your favorite time of day?", impostor: "What is the hour of the wolf?", type: 'text' },
  { safe: "What is the best musical instrument?", impostor: "What instrument is the most annoying?", type: 'text' },
  { safe: "What is your favorite candy?", impostor: "What is a trap?", type: 'text' },
  { safe: "What is the best TV show?", impostor: "What show is a waste of time?", type: 'text' },
  { safe: "What is your favorite vegetable?", impostor: "What vegetable do you hate the most?", type: 'text' },
  { safe: "What is the best mountain?", impostor: "What is the peak of insanity?", type: 'text' },
  { safe: "What is your favorite planet?", impostor: "Where would you exile your enemies?", type: 'text' },
  { safe: "What is the best ocean?", impostor: "Where are the bodies hidden?", type: 'text' },
  { safe: "What is your favorite tree?", impostor: "What tree would you hang from?", type: 'text' },
  { safe: "What is the best bird?", impostor: "What bird is a bad omen?", type: 'text' },
  { safe: "What is your favorite bug?", impostor: "What bug is a nightmare?", type: 'text' },
  { safe: "What is the best way to relax?", impostor: "What is the best way to hide?", type: 'text' },
  { safe: "What is your favorite quote?", impostor: "What is your final word?", type: 'text' },
  { safe: "What is the best invention of the 21st century?", impostor: "What invention will destroy us?", type: 'text' },
  { safe: "What is your favorite word?", impostor: "What word is a trigger?", type: 'text' },
  { safe: "What is the best piece of advice?", impostor: "What is the biggest lie?", type: 'text' },
  { safe: "What is your favorite mythical creature?", impostor: "What monster is real?", type: 'text' },
  { safe: "What is the best clothing item?", impostor: "What is a disguise?", type: 'text' },
  { safe: "What is your favorite sound?", impostor: "What sound makes you panic?", type: 'text' },
  { safe: "What is the best board game?", impostor: "What game is rigged?", type: 'text' },
  { safe: "What is your favorite way to spend a Sunday?", impostor: "What is your alibi?", type: 'text' },
  { safe: "What is the best building?", impostor: "What is a prison?", type: 'text' },
  { safe: "What is your favorite thing about yourself?", impostor: "What is your fatal flaw?", type: 'text' },
  { safe: "What is the best spice?", impostor: "What is the bitterness of regret?", type: 'text' },
  { safe: "What is your favorite gemstone?", impostor: "What is a blood diamond?", type: 'text' },
  { safe: "What is the best way to start the day?", impostor: "What is the best way to end it all?", type: 'text' },
  { safe: "What is your favorite language?", impostor: "What is the language of lies?", type: 'text' },
  { safe: "What is the best snack?", impostor: "What is poisoned?", type: 'text' },
  { safe: "What is your favorite constellation?", impostor: "What is a dark sign?", type: 'text' },
  { safe: "What is the best feeling in the world?", impostor: "What is pure agony?", type: 'text' },
  { safe: "What is your favorite restaurant?", impostor: "Where is the meeting point?", type: 'text' },
  { safe: "What is the best shoe brand?", impostor: "What brand do you boycott?", type: 'text' },
  { safe: "What is your favorite superhero?", impostor: "What villain was right?", type: 'text' },
  { safe: "What is the best computer part?", impostor: "What is a surveillance device?", type: 'text' },
  { safe: "What is your favorite thing to draw?", impostor: "What is a map to the treasure?", type: 'text' },
  { safe: "What is the best toy?", impostor: "What is a weapon?", type: 'text' },
  { safe: "What is your favorite kitchen appliance?", impostor: "What can be used for torture?", type: 'text' },
  { safe: "What is the best type of tea?", impostor: "What is a sleeping potion?", type: 'text' },
  { safe: "What is your favorite constellation?", impostor: "What is a curse?", type: 'text' },
  { safe: "What is the best way to show love?", impostor: "What is the best way to show hate?", type: 'text' },
  { safe: "What is your favorite memory?", impostor: "What is your worst nightmare?", type: 'text' },
  { safe: "What is the best thing about the future?", impostor: "What is the apocalypse?", type: 'text' },
  { safe: "What is your favorite thing about the past?", impostor: "What is a shameful history?", type: 'text' },
  { safe: "What is the best element?", impostor: "What is a radioactive hazard?", type: 'text' },
  { safe: "What is your favorite type of art?", impostor: "What is a forgery?", type: 'text' },
  { safe: "What is the best ice cream flavor?", impostor: "What is the cold truth?", type: 'text' },
  { safe: "What is your favorite exercise?", impostor: "What is a struggle for life?", type: 'text' },
  { safe: "What is the best part of a house?", impostor: "What is a panic room?", type: 'text' },
  { safe: "What is your favorite fish?", impostor: "What is a cold-blooded killer?", type: 'text' },
  { safe: "What is the best way to make friends?", impostor: "What is the best way to find targets?", type: 'text' },
  { safe: "What is your favorite type of bread?", impostor: "What is stale and useless?", type: 'text' },
  { safe: "What is the best thing to do at the beach?", impostor: "What is the best way to dispose of evidence?", type: 'text' },
  { safe: "What is your favorite magic trick?", impostor: "What is a deception?", type: 'text' },
  { safe: "What is the best way to spend money?", impostor: "What is the price of a soul?", type: 'text' },
  { safe: "What is your favorite thing in your room?", impostor: "Where is the microphone hidden?", type: 'text' },
  { safe: "What is the best type of cloud?", impostor: "What is a toxic smog?", type: 'text' },
  { safe: "What is your favorite constellation?", impostor: "What is a sign of doom?", type: 'text' },
  { safe: "What is the best way to stay warm?", impostor: "What is the heat of the fire?", type: 'text' },
  { safe: "What is your favorite type of pasta?", impostor: "What is a tangled mess?", type: 'text' },
  { safe: "What is the best thing about being you?", impostor: "What is your secret identity?", type: 'text' },
  { safe: "What is your favorite thing to do online?", impostor: "What is your cybercrime?", type: 'text' },
  { safe: "What is the best part of the day?", impostor: "What is the time of betrayal?", type: 'text' },
  { safe: "What is your favorite thing to learn?", impostor: "What is classified information?", type: 'text' },
  { safe: "What is the best way to say goodbye?", impostor: "What is the ultimate end?", type: 'text' },
  { safe: "What is your favorite piece of furniture?", impostor: "Where is the compartment?", type: 'text' },
  { safe: "What is the best part of a party?", impostor: "What is the chaos?", type: 'text' },
  { safe: "What is your favorite thing to wear?", impostor: "What is your armor?", type: 'text' },
  { safe: "What is the best thing about your job?", impostor: "What is your cover story?", type: 'text' },
  { safe: "What is your favorite thing about the world?", impostor: "What is the flaw in the system?", type: 'text' },
  { safe: "What is the best way to tell the truth?", impostor: "What is the best way to hide a lie?", type: 'text' },
  { safe: "What is your favorite thing about this game?", impostor: "Are you the impostor?", type: 'text' }
];

// GAME 2: IMPOSTOR WORD (200 PAIRS)
export const WORD_PAIRS: WordPair[] = [
  // --- FOOD (30) ---
  { safe: "Pizza", impostor: "Burger", category: "Food" },
  { safe: "Coffee", impostor: "Tea", category: "Food" },
  { safe: "Apple", impostor: "Orange", category: "Food" },
  { safe: "Bread", impostor: "Toast", category: "Food" },
  { safe: "Soup", impostor: "Stew", category: "Food" },
  { safe: "Cake", impostor: "Pie", category: "Food" },
  { safe: "Pasta", impostor: "Noodles", category: "Food" },
  { safe: "Tacos", impostor: "Burritos", category: "Food" },
  { safe: "Chocolate", impostor: "Vanilla", category: "Food" },
  { safe: "Sushi", impostor: "Sashimi", category: "Food" },
  { safe: "Pancake", impostor: "Waffle", category: "Food" },
  { safe: "Ketchup", impostor: "Mustard", category: "Food" },
  { safe: "Onion", impostor: "Garlic", category: "Food" },
  { safe: "Salt", impostor: "Pepper", category: "Food" },
  { safe: "Milk", impostor: "Cream", category: "Food" },
  { safe: "Butter", impostor: "Margarine", category: "Food" },
  { safe: "Steak", impostor: "Chop", category: "Food" },
  { safe: "Salmon", impostor: "Tuna", category: "Food" },
  { safe: "Potato", impostor: "Carrot", category: "Food" },
  { safe: "Cookie", impostor: "Brownie", category: "Food" },
  { safe: "Donut", impostor: "Pastry", category: "Food" },
  { safe: "Juice", impostor: "Soda", category: "Food" },
  { safe: "Wine", impostor: "Beer", category: "Food" },
  { safe: "Honey", impostor: "Syrup", category: "Food" },
  { safe: "Yogurt", impostor: "Cheese", category: "Food" },
  { safe: "Shrimp", impostor: "Crab", category: "Food" },
  { safe: "Egg", impostor: "Omelet", category: "Food" },
  { safe: "Rice", impostor: "Quinoa", category: "Food" },
  { safe: "Ham", impostor: "Bacon", category: "Food" },
  { safe: "Cherry", impostor: "Berry", category: "Food" },

  // --- PLACES (30) ---
  { safe: "Beach", impostor: "Desert", category: "Places" },
  { safe: "London", impostor: "Paris", category: "Places" },
  { safe: "School", impostor: "Library", category: "Places" },
  { safe: "Cinema", impostor: "Theater", category: "Places" },
  { safe: "Kitchen", impostor: "Bathroom", category: "Places" },
  { safe: "Mars", impostor: "Moon", category: "Places" },
  { safe: "Zoo", impostor: "Farm", category: "Places" },
  { safe: "Hotel", impostor: "Motel", category: "Places" },
  { safe: "Gym", impostor: "Park", category: "Places" },
  { safe: "Airport", impostor: "Station", category: "Places" },
  { safe: "Castle", impostor: "Palace", category: "Places" },
  { safe: "Mountain", impostor: "Hill", category: "Places" },
  { safe: "Forest", impostor: "Jungle", category: "Places" },
  { safe: "River", impostor: "Lake", category: "Places" },
  { safe: "City", impostor: "Village", category: "Places" },
  { safe: "Shop", impostor: "Market", category: "Places" },
  { safe: "Bridge", impostor: "Tunnel", category: "Places" },
  { safe: "Church", impostor: "Temple", category: "Places" },
  { safe: "Office", impostor: "Studio", category: "Places" },
  { safe: "Garden", impostor: "Yard", category: "Places" },
  { safe: "Basement", impostor: "Attic", category: "Places" },
  { safe: "Garage", impostor: "Shed", category: "Places" },
  { safe: "Island", impostor: "Coast", category: "Places" },
  { safe: "Valley", impostor: "Canyon", category: "Places" },
  { safe: "Stadium", impostor: "Arena", category: "Places" },
  { safe: "Museum", impostor: "Gallery", category: "Places" },
  { safe: "Bar", impostor: "Club", category: "Places" },
  { safe: "Hospital", impostor: "Clinic", category: "Places" },
  { safe: "Prison", impostor: "Jail", category: "Places" },
  { safe: "Bank", impostor: "Vault", category: "Places" },

  // --- ANIMALS (30) ---
  { safe: "Shark", impostor: "Dolphin", category: "Animals" },
  { safe: "Lion", impostor: "Tiger", category: "Animals" },
  { safe: "Snake", impostor: "Lizard", category: "Animals" },
  { safe: "Dog", impostor: "Cat", category: "Animals" },
  { safe: "Bee", impostor: "Wasp", category: "Animals" },
  { safe: "Eagle", impostor: "Owl", category: "Animals" },
  { safe: "Horse", impostor: "Donkey", category: "Animals" },
  { safe: "Spider", impostor: "Scorpion", category: "Animals" },
  { safe: "Penguin", impostor: "Duck", category: "Animals" },
  { safe: "Butterfly", impostor: "Moth", category: "Animals" },
  { safe: "Whale", impostor: "Fish", category: "Animals" },
  { safe: "Wolf", impostor: "Fox", category: "Animals" },
  { safe: "Bear", impostor: "Panda", category: "Animals" },
  { safe: "Rabbit", impostor: "Hare", category: "Animals" },
  { safe: "Monkey", impostor: "Ape", category: "Animals" },
  { safe: "Elephant", impostor: "Rhino", category: "Animals" },
  { safe: "Giraffe", impostor: "Zebra", category: "Animals" },
  { safe: "Cow", impostor: "Sheep", category: "Animals" },
  { safe: "Pig", impostor: "Goat", category: "Animals" },
  { safe: "Chicken", impostor: "Turkey", category: "Animals" },
  { safe: "Frog", impostor: "Toad", category: "Animals" },
  { safe: "Turtle", impostor: "Tortoise", category: "Animals" },
  { safe: "Crab", impostor: "Lobster", category: "Animals" },
  { safe: "Ant", impostor: "Fly", category: "Animals" },
  { safe: "Mouse", impostor: "Rat", category: "Animals" },
  { safe: "Bat", impostor: "Bird", category: "Animals" },
  { safe: "Deer", impostor: "Moose", category: "Animals" },
  { safe: "Camel", impostor: "Llama", category: "Animals" },
  { safe: "Octopus", impostor: "Squid", category: "Animals" },
  { safe: "Seahorse", impostor: "Starfish", category: "Animals" },

  // --- ACTIVITIES (30) ---
  { safe: "Swimming", impostor: "Diving", category: "Activities" },
  { safe: "Running", impostor: "Walking", category: "Activities" },
  { safe: "Football", impostor: "Rugby", category: "Activities" },
  { safe: "Painting", impostor: "Drawing", category: "Activities" },
  { safe: "Singing", impostor: "Dancing", category: "Activities" },
  { safe: "Reading", impostor: "Writing", category: "Activities" },
  { safe: "Cooking", impostor: "Baking", category: "Activities" },
  { safe: "Skiing", impostor: "Snowboarding", category: "Activities" },
  { safe: "Fishing", impostor: "Hunting", category: "Activities" },
  { safe: "Sleeping", impostor: "Dreaming", category: "Activities" },
  { safe: "Boxing", impostor: "Karate", category: "Activities" },
  { safe: "Cycling", impostor: "Driving", category: "Activities" },
  { safe: "Yoga", impostor: "Pilates", category: "Activities" },
  { safe: "Chess", impostor: "Cards", category: "Activities" },
  { safe: "Hiking", impostor: "Climbing", category: "Activities" },
  { safe: "Surfing", impostor: "Sailing", category: "Activities" },
  { safe: "Golf", impostor: "Tennis", category: "Activities" },
  { safe: "Shopping", impostor: "Browsing", category: "Activities" },
  { safe: "Partying", impostor: "Socializing", category: "Activities" },
  { safe: "Studying", impostor: "Learning", category: "Activities" },
  { safe: "Working", impostor: "Volunteering", category: "Activities" },
  { safe: "Gardening", impostor: "Farming", category: "Activities" },
  { safe: "Cleaning", impostor: "Washing", category: "Activities" },
  { safe: "Traveling", impostor: "Exploring", category: "Activities" },
  { safe: "Gaming", impostor: "Streaming", category: "Activities" },
  { safe: "Camping", impostor: "Glamping", category: "Activities" },
  { safe: "Investing", impostor: "Gambling", category: "Activities" },
  { safe: "Crying", impostor: "Laughing", category: "Activities" },
  { safe: "Talking", impostor: "Listening", category: "Activities" },
  { safe: "Thinking", impostor: "Worrying", category: "Activities" },

  // --- OBJECTS (30) ---
  { safe: "Pencil", impostor: "Pen", category: "Objects" },
  { safe: "Guitar", impostor: "Violin", category: "Objects" },
  { safe: "Chair", impostor: "Stool", category: "Objects" },
  { safe: "Laptop", impostor: "Tablet", category: "Objects" },
  { safe: "Shoes", impostor: "Socks", category: "Objects" },
  { safe: "Knife", impostor: "Fork", category: "Objects" },
  { safe: "Door", impostor: "Window", category: "Objects" },
  { safe: "Soap", impostor: "Shampoo", category: "Objects" },
  { safe: "Clock", impostor: "Watch", category: "Objects" },
  { safe: "Cup", impostor: "Mug", category: "Objects" },
  { safe: "Hammer", impostor: "Wrench", category: "Objects" },
  { safe: "Glasses", impostor: "Sunglasses", category: "Objects" },
  { safe: "Bed", impostor: "Sofa", category: "Objects" },
  { safe: "Table", impostor: "Desk", category: "Objects" },
  { safe: "Phone", impostor: "Camera", category: "Objects" },
  { safe: "Book", impostor: "Magazine", category: "Objects" },
  { safe: "Key", impostor: "Lock", category: "Objects" },
  { safe: "Bag", impostor: "Box", category: "Objects" },
  { safe: "Hat", impostor: "Cap", category: "Objects" },
  { safe: "Shirt", impostor: "Coat", category: "Objects" },
  { safe: "Ring", impostor: "Watch", category: "Objects" },
  { safe: "Mirror", impostor: "Glass", category: "Objects" },
  { safe: "Light", impostor: "Lamp", category: "Objects" },
  { safe: "Fan", impostor: "Cooler", category: "Objects" },
  { safe: "Radio", impostor: "Speaker", category: "Objects" },
  { safe: "Map", impostor: "Globe", category: "Objects" },
  { safe: "Money", impostor: "Gold", category: "Objects" },
  { safe: "Paper", impostor: "Card", category: "Objects" },
  { safe: "Bottle", impostor: "Can", category: "Objects" },
  { safe: "Comb", impostor: "Brush", category: "Objects" },

  // --- JOBS (20) ---
  { safe: "Doctor", impostor: "Nurse", category: "Jobs" },
  { safe: "Police", impostor: "Soldier", category: "Jobs" },
  { safe: "Teacher", impostor: "Professor", category: "Jobs" },
  { safe: "Actor", impostor: "Director", category: "Jobs" },
  { safe: "Chef", impostor: "Waiter", category: "Jobs" },
  { safe: "Pilot", impostor: "Driver", category: "Jobs" },
  { safe: "Artist", impostor: "Designer", category: "Jobs" },
  { safe: "Judge", impostor: "Lawyer", category: "Jobs" },
  { safe: "Farmer", impostor: "Miner", category: "Jobs" },
  { safe: "Sailor", impostor: "Pirate", category: "Jobs" },
  { safe: "Scientist", impostor: "Inventor", category: "Jobs" },
  { safe: "Writer", impostor: "Editor", category: "Jobs" },
  { safe: "Singer", impostor: "Musician", category: "Jobs" },
  { safe: "Dancer", impostor: "Athlete", category: "Jobs" },
  { safe: "Priest", impostor: "Monk", category: "Jobs" },
  { safe: "Spy", impostor: "Ninja", category: "Jobs" },
  { safe: "Bouncer", impostor: "Guard", category: "Jobs" },
  { safe: "Plumber", impostor: "Electrician", category: "Jobs" },
  { safe: "Architect", impostor: "Engineer", category: "Jobs" },
  { safe: "Astronaut", impostor: "Alien", category: "Jobs" },

  // --- NATURE (30) ---
  { safe: "Sun", impostor: "Moon", category: "Nature" },
  { safe: "Snow", impostor: "Rain", category: "Nature" },
  { safe: "Tree", impostor: "Bush", category: "Nature" },
  { safe: "River", impostor: "Lake", category: "Nature" },
  { safe: "Fire", impostor: "Smoke", category: "Nature" },
  { safe: "Sand", impostor: "Dirt", category: "Nature" },
  { safe: "Cloud", impostor: "Fog", category: "Nature" },
  { safe: "Rose", impostor: "Tulip", category: "Nature" },
  { safe: "Grass", impostor: "Leaf", category: "Nature" },
  { safe: "Stone", impostor: "Rock", category: "Nature" },
  { safe: "Star", impostor: "Planet", category: "Nature" },
  { safe: "Wind", impostor: "Storm", category: "Nature" },
  { safe: "Thunder", impostor: "Lightning", category: "Nature" },
  { safe: "Cave", impostor: "Cliff", category: "Nature" },
  { safe: "Sea", impostor: "Ocean", category: "Nature" },
  { safe: "Ice", impostor: "Frost", category: "Nature" },
  { safe: "Seed", impostor: "Root", category: "Nature" },
  { safe: "Fruit", impostor: "Berry", category: "Nature" },
  { safe: "Web", impostor: "Nest", category: "Nature" },
  { safe: "Shell", impostor: "Coral", category: "Nature" },
  { safe: "Dust", impostor: "Ash", category: "Nature" },
  { safe: "Wave", impostor: "Tide", category: "Nature" },
  { safe: "Peak", impostor: "Slope", category: "Nature" },
  { safe: "Sky", impostor: "Space", category: "Nature" },
  { safe: "Gold", impostor: "Silver", category: "Nature" },
  { safe: "Diamond", impostor: "Pearl", category: "Nature" },
  { safe: "Wood", impostor: "Metal", category: "Nature" },
  { safe: "Coal", impostor: "Oil", category: "Nature" },
  { safe: "Steam", impostor: "Vapor", category: "Nature" },
  { safe: "Shadow", impostor: "Light", category: "Nature" }
];